### ISSUE TITLE
opam install failed

### ISSUE THREAD

**Issue by gessig** [bobbypriambodo/ezpostgresql#1]
I tried the following opam command in the readme and it didn't work:

opam pin add ezpostgresql git+https://github.com/bobbypriambodo/ezpostgresql.git

Removing 'git+' did work however.  The command is then:

opam pin add ezpostgresql https://github.com/bobbypriambodo/ezpostgresql.git

Maybe the readme should be updated.

**Comment by bobbypriambodo** [comment]
Thanks for reporting! It would seem the `git+https://` form works only on opam2. I have fixed the readme instruction.
